"""aviation_chronicle_is_approve_add

Revision ID: 19ba0070e7d5
Revises: 01e9e6875f39
Create Date: 2026-10-08 16:47:17.713532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ba0070e7d5'
down_revision: Union[str, Sequence[str], None] = '01e9e6875f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aviation_chronicle', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('aviation_chronicle', sa.Column('is_approved_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'aviation_chronicle', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'aviation_chronicle', type_='unique')
    op.drop_column('aviation_chronicle', 'is_approved_time')
    op.drop_column('aviation_chronicle', 'is_approved')
    # ### end Alembic commands ###
