"""remove_extra_fields

Revision ID: 378cc24b2674
Revises: 58661600cc2f
Create Date: 2026-09-29 14:49:01.497853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378cc24b2674'
down_revision: Union[str, Sequence[str], None] = '58661600cc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'licence_type')
    op.drop_column('manufacturers', 'author_name')
    op.drop_column('manufacturers', 'wiki_link')
    op.drop_column('manufacturers', 'products_2')
    op.drop_column('manufacturers', 'products_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('products_1', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('products_2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('wiki_link', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('manufacturers', sa.Column('licence_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
