"""add_field_aircraft

Revision ID: 3848ab13c24a
Revises: ae54dfb48ffc
Create Date: 2026-09-30 15:50:26.445096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3848ab13c24a'
down_revision: Union[str, Sequence[str], None] = 'ae54dfb48ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aircrafts', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('aircrafts', sa.Column('is_approved_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'aircrafts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'aircrafts', type_='unique')
    op.drop_column('aircrafts', 'is_approved_time')
    op.drop_column('aircrafts', 'is_approved')
    # ### end Alembic commands ###
