"""add_field_approve_time

Revision ID: 58661600cc2f
Revises: f5db10b3b7d0
Create Date: 2026-09-29 13:46:29.347616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58661600cc2f'
down_revision: Union[str, Sequence[str], None] = 'f5db10b3b7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('is_approved_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'is_approved_time')
    # ### end Alembic commands ###
