"""create_manufacture_model

Revision ID: 5b7c988afffb
Revises: ff5f9638c6e6
Create Date: 2026-09-28 15:37:26.721463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b7c988afffb'
down_revision: Union[str, Sequence[str], None] = 'ff5f9638c6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('headquarter', sa.String(), nullable=True),
    sa.Column('founding_date', sa.String(), nullable=True),
    sa.Column('cover_photo', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('company_history', sa.Text(), nullable=True),
    sa.Column('interesting_facts', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('products_1', sa.Text(), nullable=True),
    sa.Column('products_2', sa.Text(), nullable=True),
    sa.Column('licence_type', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('wiki_link', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_company_name'), 'manufacturers', ['company_name'], unique=True)
    op.create_table('products',
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('manufacturer_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_index(op.f('ix_manufacturers_company_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
