"""add_field_is_approved

Revision ID: 62d329af37b3
Revises: aa6a0ffc4af5
Create Date: 2026-10-06 20:15:26.225182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d329af37b3'
down_revision: Union[str, Sequence[str], None] = 'aa6a0ffc4af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports_data', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('airports_data', sa.Column('is_approved_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'airports_data', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'airports_data', type_='unique')
    op.drop_column('airports_data', 'is_approved_time')
    op.drop_column('airports_data', 'is_approved')
    # ### end Alembic commands ###
