"""add_is_approve_glossary

Revision ID: 636e2550d97e
Revises: 724dfb97d4ad
Create Date: 2026-10-09 13:03:34.602728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636e2550d97e'
down_revision: Union[str, Sequence[str], None] = '724dfb97d4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glossary', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('glossary', sa.Column('is_approved_time', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'glossary', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'glossary', type_='unique')
    op.drop_column('glossary', 'is_approved_time')
    op.drop_column('glossary', 'is_approved')
    # ### end Alembic commands ###
