"""add_airport_model

Revision ID: aa6a0ffc4af5
Revises: 4f531aaa1609
Create Date: 2026-10-06 19:46:58.141514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6a0ffc4af5'
down_revision: Union[str, Sequence[str], None] = '4f531aaa1609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports_data',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('latitude_deg', sa.Float(), nullable=False),
    sa.Column('longitude_deg', sa.Float(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('utc_offset', sa.String(length=50), nullable=True),
    sa.Column('iata_code', sa.String(length=50), nullable=True),
    sa.Column('icao', sa.String(length=50), nullable=True),
    sa.Column('number_of_runways', sa.String(), nullable=True),
    sa.Column('runway_direction', sa.String(length=50), nullable=True),
    sa.Column('runway_length', sa.String(), nullable=True),
    sa.Column('elev', sa.String(), nullable=True),
    sa.Column('runway_surface_type', sa.String(length=100), nullable=True),
    sa.Column('number_of_terminals', sa.String(length=50), nullable=True),
    sa.Column('annual_movements', sa.String(length=50), nullable=True),
    sa.Column('annual_passenger_traffic', sa.String(length=50), nullable=True),
    sa.Column('airport_weather', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata_code', 'icao', name='uq_airport_codes'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_airports_data_iata_code'), 'airports_data', ['iata_code'], unique=False)
    op.create_index(op.f('ix_airports_data_icao'), 'airports_data', ['icao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airports_data_icao'), table_name='airports_data')
    op.drop_index(op.f('ix_airports_data_iata_code'), table_name='airports_data')
    op.drop_table('airports_data')
    # ### end Alembic commands ###
