"""add_model_aircraft

Revision ID: ae54dfb48ffc
Revises: 378cc24b2674
Create Date: 2026-09-29 19:59:53.797776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae54dfb48ffc'
down_revision: Union[str, Sequence[str], None] = '378cc24b2674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircrafts',
    sa.Column('images', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('manufacturer_id', sa.String(), nullable=False),
    sa.Column('ICAO_Type_Code', sa.String(), nullable=True),
    sa.Column('Aircraft_Model', sa.String(), nullable=True),
    sa.Column('Aircraft_Role', sa.String(), nullable=True),
    sa.Column('Aircraft_Type', sa.String(), nullable=True),
    sa.Column('Wake_Turbulence_Category', sa.String(), nullable=True),
    sa.Column('Civilian_Military_or_Dual_Use', sa.String(), nullable=True),
    sa.Column('Country_of_Origin', sa.String(), nullable=True),
    sa.Column('Date_of_Maiden_Flight', sa.Date(), nullable=True),
    sa.Column('Year_of_Introduction', sa.String(), nullable=True),
    sa.Column('Production_Status', sa.String(), nullable=True),
    sa.Column('Avionics_System', sa.String(), nullable=True),
    sa.Column('Number_of_Crew', sa.String(), nullable=True),
    sa.Column('Number_of_Passengers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('Number_of_Engines', sa.Integer(), nullable=True),
    sa.Column('Engine', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('APU_Type', sa.String(), nullable=True),
    sa.Column('Fuel', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('Wingspan_m', sa.String(), nullable=True),
    sa.Column('Wingspan_ft', sa.String(), nullable=True),
    sa.Column('Length_m', sa.String(), nullable=True),
    sa.Column('Length_ft', sa.String(), nullable=True),
    sa.Column('Height_m', sa.String(), nullable=True),
    sa.Column('Height_ft', sa.String(), nullable=True),
    sa.Column('Wing_Area_m2', sa.String(), nullable=True),
    sa.Column('Cabin_Width_m', sa.String(), nullable=True),
    sa.Column('Door_Height_m', sa.String(), nullable=True),
    sa.Column('Wingtip_Configuration', sa.String(), nullable=True),
    sa.Column('Operating_Empty_Weight_kg', sa.String(), nullable=True),
    sa.Column('Maximum_Zero_Fuel_Weight_kg', sa.String(), nullable=True),
    sa.Column('Maximum_Takeoff_Weight_kg', sa.String(), nullable=True),
    sa.Column('Maximum_Payload_kg', sa.String(), nullable=True),
    sa.Column('Maximum_Landing_Weight_kg', sa.String(), nullable=True),
    sa.Column('Baggage_or_Cargo_Volume', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('Takeoff_Speed_kts', sa.String(), nullable=True),
    sa.Column('Takeoff_Distance_m', sa.String(), nullable=True),
    sa.Column('Initial_Climb_Rate_fpm', sa.String(), nullable=True),
    sa.Column('Average_Rate_of_Climb_fpm', sa.String(), nullable=True),
    sa.Column('Maximum_Rate_of_Climb_fpm', sa.String(), nullable=True),
    sa.Column('Service_Ceiling_ft', sa.String(), nullable=True),
    sa.Column('Max_Certified_Altitude_ft', sa.String(), nullable=True),
    sa.Column('Cruise_Speed_kt', sa.String(), nullable=True),
    sa.Column('Cruise_Mach', sa.String(), nullable=True),
    sa.Column('Maximum_Cruise_Speed_kts_or_Mach', sa.String(), nullable=True),
    sa.Column('VMO_kts', sa.String(), nullable=True),
    sa.Column('MMO_Mach', sa.String(), nullable=True),
    sa.Column('Range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('Initial_Rate_of_Descent_fpm', sa.String(), nullable=True),
    sa.Column('Average_Rate_of_Descent_fpm', sa.String(), nullable=True),
    sa.Column('Minimum_Clean_Speed_kts', sa.String(), nullable=True),
    sa.Column('Approach_Speed_kts', sa.String(), nullable=True),
    sa.Column('Approach_Category', sa.String(), nullable=True),
    sa.Column('Landing_Speed_kts', sa.String(), nullable=True),
    sa.Column('Landing_Distance_m', sa.String(), nullable=True),
    sa.Column('Runway_Length_Required_m', sa.String(), nullable=True),
    sa.Column('Stall_Speed_kts', sa.String(), nullable=True),
    sa.Column('Runway_Slope_Limit_percent', sa.String(), nullable=True),
    sa.Column('Max_Crosswind_Normal_Law_kts', sa.String(), nullable=True),
    sa.Column('Max_Crosswind_Degraded_Law_kts', sa.String(), nullable=True),
    sa.Column('Max_Tailwind_Landing_kts', sa.String(), nullable=True),
    sa.Column('Max_Tailwind_Takeoff_kts', sa.String(), nullable=True),
    sa.Column('Field_Elevation_Limit_ft', sa.String(), nullable=True),
    sa.Column('Max_Runway_Altitude_ft', sa.String(), nullable=True),
    sa.Column('Autoland_Capability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('Type', sa.String(), nullable=True),
    sa.Column('Number_of_Wheels', sa.String(), nullable=True),
    sa.Column('Tyre_Size_inches', sa.String(), nullable=True),
    sa.Column('Tyre_Pressure_bar_psi', sa.String(), nullable=True),
    sa.Column('Certification_Basis', sa.String(), nullable=True),
    sa.Column('EASA_TCDS_Number', sa.String(), nullable=True),
    sa.Column('FAA_TCDS_Number', sa.String(), nullable=True),
    sa.Column('Special_Conditions', sa.String(), nullable=True),
    sa.Column('Noise_Compliance', sa.String(), nullable=True),
    sa.Column('Emissions_Category', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Aircraft_Model'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_aircrafts_manufacturer_id'), 'aircrafts', ['manufacturer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aircrafts_manufacturer_id'), table_name='aircrafts')
    op.drop_table('aircrafts')
    # ### end Alembic commands ###
