"""update_field

Revision ID: b00a693159b3
Revises: 3848ab13c24a
Create Date: 2026-09-30 18:49:49.380204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00a693159b3'
down_revision: Union[str, Sequence[str], None] = '3848ab13c24a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('aircrafts_manufacturer_id_fkey'), 'aircrafts', type_='foreignkey')
    op.create_foreign_key(None, 'aircrafts', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'aircrafts', type_='foreignkey')
    op.create_foreign_key(op.f('aircrafts_manufacturer_id_fkey'), 'aircrafts', 'manufacturers', ['manufacturer_id'], ['id'])
    # ### end Alembic commands ###
